package com.allets.backend.data.server.entity.common;// default package
// Generated 2015. 8. 15 오후 5:46:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * AlbumBookmark generated by hbm2java
 */
@Entity
@Table(name="ALBUM_BOOKMARK"
    ,catalog="allets_common"
)
public class AlbumBookmark  implements java.io.Serializable {


     private Long id;
     private Long aid;
     private Long bid;
     private Date cdate;

    public AlbumBookmark() {
    }

	
    public AlbumBookmark(Date cdate) {
        this.cdate = cdate;
    }
    public AlbumBookmark(Long aid, Long bid, Date cdate) {
       this.aid = aid;
       this.bid = bid;
       this.cdate = cdate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="aid")
    public Long getAid() {
        return this.aid;
    }
    
    public void setAid(Long aid) {
        this.aid = aid;
    }
    
    @Column(name="bid")
    public Long getBid() {
        return this.bid;
    }
    
    public void setBid(Long bid) {
        this.bid = bid;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cdate", nullable=false, length=19)
    public Date getCdate() {
        return this.cdate;
    }
    
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }




}


