package com.allets.backend.data.server.entity.common;// default package
// Generated 2015. 8. 15 오후 5:46:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * BestContentsResultId generated by hbm2java
 */
@Embeddable
public class BestContentsResultId  implements java.io.Serializable {


     private int batchCount;
     private long contentsId;

    public BestContentsResultId() {
    }

    public BestContentsResultId(int batchCount, long contentsId) {
       this.batchCount = batchCount;
       this.contentsId = contentsId;
    }
   

    @Column(name="batch_count", nullable=false)
    public int getBatchCount() {
        return this.batchCount;
    }
    
    public void setBatchCount(int batchCount) {
        this.batchCount = batchCount;
    }

    @Column(name="contents_id", nullable=false)
    public long getContentsId() {
        return this.contentsId;
    }
    
    public void setContentsId(long contentsId) {
        this.contentsId = contentsId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BestContentsResultId) ) return false;
		 BestContentsResultId castOther = ( BestContentsResultId ) other; 
         
		 return (this.getBatchCount()==castOther.getBatchCount())
 && (this.getContentsId()==castOther.getContentsId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBatchCount();
         result = 37 * result + (int) this.getContentsId();
         return result;
   }   


}


