package com.allets.backend.data.server.entity.common;// default package
// Generated 2015. 8. 15 오후 5:46:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MgCard generated by hbm2java
 */
@Entity
@Table(name="MG_CARD"
    ,catalog="allets_common"
)
public class MgCard  implements java.io.Serializable {


     private Long cardId;
     private Long contentsId;
     private String status;
     private String title;
     private String description;
     private String url;
     private String cardType;
     private Integer ordering;
     private String sourceUrl;
     private String sourceText;
     private String videoThumbnailUrl;
     private Integer startTime;
     private Integer endTime;
     private String length;
     private Date cdate;
     private Boolean downBlocked;
     private Boolean shapeType;
     private Boolean autoPlaying;
     private Boolean autoPaging;
     private Byte repeatCount;

    public MgCard() {
    }

	
    public MgCard(String status, String cardType, Date cdate) {
        this.status = status;
        this.cardType = cardType;
        this.cdate = cdate;
    }
    public MgCard(Long contentsId, String status, String title, String description, String url, String cardType, Integer ordering, String sourceUrl, String sourceText, String videoThumbnailUrl, Integer startTime, Integer endTime, String length, Date cdate, Boolean downBlocked, Boolean shapeType, Boolean autoPlaying, Boolean autoPaging, Byte repeatCount) {
       this.contentsId = contentsId;
       this.status = status;
       this.title = title;
       this.description = description;
       this.url = url;
       this.cardType = cardType;
       this.ordering = ordering;
       this.sourceUrl = sourceUrl;
       this.sourceText = sourceText;
       this.videoThumbnailUrl = videoThumbnailUrl;
       this.startTime = startTime;
       this.endTime = endTime;
       this.length = length;
       this.cdate = cdate;
       this.downBlocked = downBlocked;
       this.shapeType = shapeType;
       this.autoPlaying = autoPlaying;
       this.autoPaging = autoPaging;
       this.repeatCount = repeatCount;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="card_id", unique=true, nullable=false)
    public Long getCardId() {
        return this.cardId;
    }
    
    public void setCardId(Long cardId) {
        this.cardId = cardId;
    }
    
    @Column(name="contents_id")
    public Long getContentsId() {
        return this.contentsId;
    }
    
    public void setContentsId(Long contentsId) {
        this.contentsId = contentsId;
    }
    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="title", length=200)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="description", length=4096)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="url", length=1000)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="card_type", nullable=false, length=10)
    public String getCardType() {
        return this.cardType;
    }
    
    public void setCardType(String cardType) {
        this.cardType = cardType;
    }
    
    @Column(name="ordering")
    public Integer getOrdering() {
        return this.ordering;
    }
    
    public void setOrdering(Integer ordering) {
        this.ordering = ordering;
    }
    
    @Column(name="source_url", length=200)
    public String getSourceUrl() {
        return this.sourceUrl;
    }
    
    public void setSourceUrl(String sourceUrl) {
        this.sourceUrl = sourceUrl;
    }
    
    @Column(name="source_text", length=200)
    public String getSourceText() {
        return this.sourceText;
    }
    
    public void setSourceText(String sourceText) {
        this.sourceText = sourceText;
    }
    
    @Column(name="video_thumbnail_url", length=200)
    public String getVideoThumbnailUrl() {
        return this.videoThumbnailUrl;
    }
    
    public void setVideoThumbnailUrl(String videoThumbnailUrl) {
        this.videoThumbnailUrl = videoThumbnailUrl;
    }
    
    @Column(name="start_time")
    public Integer getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Integer startTime) {
        this.startTime = startTime;
    }
    
    @Column(name="end_time")
    public Integer getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Integer endTime) {
        this.endTime = endTime;
    }
    
    @Column(name="length", length=45)
    public String getLength() {
        return this.length;
    }
    
    public void setLength(String length) {
        this.length = length;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cdate", nullable=false, length=19)
    public Date getCdate() {
        return this.cdate;
    }
    
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }
    
    @Column(name="down_blocked")
    public Boolean getDownBlocked() {
        return this.downBlocked;
    }
    
    public void setDownBlocked(Boolean downBlocked) {
        this.downBlocked = downBlocked;
    }
    
    @Column(name="shape_type")
    public Boolean getShapeType() {
        return this.shapeType;
    }
    
    public void setShapeType(Boolean shapeType) {
        this.shapeType = shapeType;
    }
    
    @Column(name="auto_playing")
    public Boolean getAutoPlaying() {
        return this.autoPlaying;
    }
    
    public void setAutoPlaying(Boolean autoPlaying) {
        this.autoPlaying = autoPlaying;
    }
    
    @Column(name="auto_paging")
    public Boolean getAutoPaging() {
        return this.autoPaging;
    }
    
    public void setAutoPaging(Boolean autoPaging) {
        this.autoPaging = autoPaging;
    }
    
    @Column(name="repeat_count")
    public Byte getRepeatCount() {
        return this.repeatCount;
    }
    
    public void setRepeatCount(Byte repeatCount) {
        this.repeatCount = repeatCount;
    }


    @Override
    public String toString() {
        return "MgCard{" +
                "cardId=" + cardId +
                ", contentsId=" + contentsId +
                ", status='" + status + '\'' +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", url='" + url + '\'' +
                ", cardType='" + cardType + '\'' +
                ", ordering=" + ordering +
                ", sourceUrl='" + sourceUrl + '\'' +
                ", sourceText='" + sourceText + '\'' +
                ", videoThumbnailUrl='" + videoThumbnailUrl + '\'' +
                ", startTime=" + startTime +
                ", endTime=" + endTime +
                ", length='" + length + '\'' +
                ", cdate=" + cdate +
                ", downBlocked=" + downBlocked +
                ", shapeType=" + shapeType +
                ", autoPlaying=" + autoPlaying +
                ", autoPaging=" + autoPaging +
                ", repeatCount=" + repeatCount +
                '}';
    }
}


