package com.allets.backend.data.server.entity.common;// default package
// Generated 2015. 8. 15 오후 5:46:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * MgContents generated by hbm2java
 */
@Entity
@Table(name="MG_CONTENTS"
    ,catalog="allets_common"
)
public class MgContents  implements java.io.Serializable {


     private Long contentsId;
     private User user;
     private String status;
     private Date udate;
     private String title;
     private String description;
     private String thumbnailUrl;
     private String coverUrl;
     private String headlineUrl;
     private String bgmSource;
     private String bgmText;
     private byte vertical;
     private Date cdate;
     private String contentsType;
     private int viewCount;
     private Date edate;
     private byte logDetail;
     private String originalText;
     private String originalUrl;
     private String thumbnailSourceText;
     private String thumbnailSourceUrl;
     private String coverSourceText;
     private String coverSourceUrl;
     private Date fdate;
     private String thumbnailBestUrl;
     private Set<BestContentsResult> bestContentsResults = new HashSet<BestContentsResult>(0);

    public MgContents() {
    }

	
    public MgContents(String status, byte vertical, Date cdate, int viewCount, byte logDetail) {
        this.status = status;
        this.vertical = vertical;
        this.cdate = cdate;
        this.viewCount = viewCount;
        this.logDetail = logDetail;
    }
    public MgContents(User user, String status, Date udate, String title, String description, String thumbnailUrl, String coverUrl, String headlineUrl, String bgmSource, String bgmText, byte vertical, Date cdate, String contentsType, int viewCount, Date edate, byte logDetail, String originalText, String originalUrl, String thumbnailSourceText, String thumbnailSourceUrl, String coverSourceText, String coverSourceUrl, Date fdate, String thumbnailBestUrl, Set<BestContentsResult> bestContentsResults) {
       this.user = user;
       this.status = status;
       this.udate = udate;
       this.title = title;
       this.description = description;
       this.thumbnailUrl = thumbnailUrl;
       this.coverUrl = coverUrl;
       this.headlineUrl = headlineUrl;
       this.bgmSource = bgmSource;
       this.bgmText = bgmText;
       this.vertical = vertical;
       this.cdate = cdate;
       this.contentsType = contentsType;
       this.viewCount = viewCount;
       this.edate = edate;
       this.logDetail = logDetail;
       this.originalText = originalText;
       this.originalUrl = originalUrl;
       this.thumbnailSourceText = thumbnailSourceText;
       this.thumbnailSourceUrl = thumbnailSourceUrl;
       this.coverSourceText = coverSourceText;
       this.coverSourceUrl = coverSourceUrl;
       this.fdate = fdate;
       this.thumbnailBestUrl = thumbnailBestUrl;
       this.bestContentsResults = bestContentsResults;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="contents_id", unique=true, nullable=false)
    public Long getContentsId() {
        return this.contentsId;
    }
    
    public void setContentsId(Long contentsId) {
        this.contentsId = contentsId;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uid")
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="udate", length=19)
    public Date getUdate() {
        return this.udate;
    }
    
    public void setUdate(Date udate) {
        this.udate = udate;
    }
    
    @Column(name="title", length=200)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    @Column(name="description", length=400)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="thumbnail_url", length=200)
    public String getThumbnailUrl() {
        return this.thumbnailUrl;
    }
    
    public void setThumbnailUrl(String thumbnailUrl) {
        this.thumbnailUrl = thumbnailUrl;
    }
    
    @Column(name="cover_url", length=200)
    public String getCoverUrl() {
        return this.coverUrl;
    }
    
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }
    
    @Column(name="headline_url", length=200)
    public String getHeadlineUrl() {
        return this.headlineUrl;
    }
    
    public void setHeadlineUrl(String headlineUrl) {
        this.headlineUrl = headlineUrl;
    }
    
    @Column(name="bgm_source", length=200)
    public String getBgmSource() {
        return this.bgmSource;
    }
    
    public void setBgmSource(String bgmSource) {
        this.bgmSource = bgmSource;
    }
    
    @Column(name="bgm_text", length=400)
    public String getBgmText() {
        return this.bgmText;
    }
    
    public void setBgmText(String bgmText) {
        this.bgmText = bgmText;
    }
    
    @Column(name="vertical", nullable=false)
    public byte getVertical() {
        return this.vertical;
    }
    
    public void setVertical(byte vertical) {
        this.vertical = vertical;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cdate", nullable=false, length=19)
    public Date getCdate() {
        return this.cdate;
    }
    
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }
    
    @Column(name="contents_type", length=10)
    public String getContentsType() {
        return this.contentsType;
    }
    
    public void setContentsType(String contentsType) {
        this.contentsType = contentsType;
    }
    
    @Column(name="view_count", nullable=false)
    public int getViewCount() {
        return this.viewCount;
    }
    
    public void setViewCount(int viewCount) {
        this.viewCount = viewCount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="edate", length=19)
    public Date getEdate() {
        return this.edate;
    }
    
    public void setEdate(Date edate) {
        this.edate = edate;
    }
    
    @Column(name="log_detail", nullable=false)
    public byte getLogDetail() {
        return this.logDetail;
    }
    
    public void setLogDetail(byte logDetail) {
        this.logDetail = logDetail;
    }
    
    @Column(name="original_text", length=200)
    public String getOriginalText() {
        return this.originalText;
    }
    
    public void setOriginalText(String originalText) {
        this.originalText = originalText;
    }
    
    @Column(name="original_url", length=200)
    public String getOriginalUrl() {
        return this.originalUrl;
    }
    
    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }
    
    @Column(name="thumbnail_source_text", length=200)
    public String getThumbnailSourceText() {
        return this.thumbnailSourceText;
    }
    
    public void setThumbnailSourceText(String thumbnailSourceText) {
        this.thumbnailSourceText = thumbnailSourceText;
    }
    
    @Column(name="thumbnail_source_url", length=200)
    public String getThumbnailSourceUrl() {
        return this.thumbnailSourceUrl;
    }
    
    public void setThumbnailSourceUrl(String thumbnailSourceUrl) {
        this.thumbnailSourceUrl = thumbnailSourceUrl;
    }
    
    @Column(name="cover_source_text", length=200)
    public String getCoverSourceText() {
        return this.coverSourceText;
    }
    
    public void setCoverSourceText(String coverSourceText) {
        this.coverSourceText = coverSourceText;
    }
    
    @Column(name="cover_source_url", length=200)
    public String getCoverSourceUrl() {
        return this.coverSourceUrl;
    }
    
    public void setCoverSourceUrl(String coverSourceUrl) {
        this.coverSourceUrl = coverSourceUrl;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="fdate", length=19)
    public Date getFdate() {
        return this.fdate;
    }
    
    public void setFdate(Date fdate) {
        this.fdate = fdate;
    }
    
    @Column(name="thumbnail_best_url", length=200)
    public String getThumbnailBestUrl() {
        return this.thumbnailBestUrl;
    }
    
    public void setThumbnailBestUrl(String thumbnailBestUrl) {
        this.thumbnailBestUrl = thumbnailBestUrl;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="mgContents")
    public Set<BestContentsResult> getBestContentsResults() {
        return this.bestContentsResults;
    }
    
    public void setBestContentsResults(Set<BestContentsResult> bestContentsResults) {
        this.bestContentsResults = bestContentsResults;
    }


    @Override
    public String toString() {
        return "MgContents{" +
                "contentsId=" + contentsId +
                ", user=" + user +
                ", status='" + status + '\'' +
                ", udate=" + udate +
                ", title='" + title + '\'' +
                ", description='" + description + '\'' +
                ", thumbnailUrl='" + thumbnailUrl + '\'' +
                ", coverUrl='" + coverUrl + '\'' +
                ", headlineUrl='" + headlineUrl + '\'' +
                ", bgmSource='" + bgmSource + '\'' +
                ", bgmText='" + bgmText + '\'' +
                ", vertical=" + vertical +
                ", cdate=" + cdate +
                ", contentsType='" + contentsType + '\'' +
                ", viewCount=" + viewCount +
                ", edate=" + edate +
                ", logDetail=" + logDetail +
                ", originalText='" + originalText + '\'' +
                ", originalUrl='" + originalUrl + '\'' +
                ", thumbnailSourceText='" + thumbnailSourceText + '\'' +
                ", thumbnailSourceUrl='" + thumbnailSourceUrl + '\'' +
                ", coverSourceText='" + coverSourceText + '\'' +
                ", coverSourceUrl='" + coverSourceUrl + '\'' +
                ", fdate=" + fdate +
                ", thumbnailBestUrl='" + thumbnailBestUrl + '\'' +
                ", bestContentsResults=" + bestContentsResults +
                '}';
    }
}


