package com.allets.backend.data.server.entity.common;// default package
// Generated 2015. 8. 15 오후 5:46:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MgCommentLikeId generated by hbm2java
 */
@Embeddable
public class MgCommentLikeId  implements java.io.Serializable {


     private long commentId;
     private long uid;

    public MgCommentLikeId() {
    }

    public MgCommentLikeId(long commentId, long uid) {
       this.commentId = commentId;
       this.uid = uid;
    }
   

    @Column(name="comment_id", nullable=false)
    public long getCommentId() {
        return this.commentId;
    }
    
    public void setCommentId(long commentId) {
        this.commentId = commentId;
    }

    @Column(name="uid", nullable=false)
    public long getUid() {
        return this.uid;
    }
    
    public void setUid(long uid) {
        this.uid = uid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MgCommentLikeId) ) return false;
		 MgCommentLikeId castOther = ( MgCommentLikeId ) other; 
         
		 return (this.getCommentId()==castOther.getCommentId())
 && (this.getUid()==castOther.getUid());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getCommentId();
         result = 37 * result + (int) this.getUid();
         return result;
   }   


}


