package com.allets.backend.data.server.entity.common;// default package
// Generated 2015. 8. 15 오후 5:46:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * MgCommentLike generated by hbm2java
 */
@Entity
@Table(name="MG_COMMENT_LIKE"
    ,catalog="allets_common"
)
public class MgCommentLike  implements java.io.Serializable {


     private MgCommentLikeId id;
     private MgComment mgComment;
     private User user;
     private Date cdate;

    public MgCommentLike() {
    }

    public MgCommentLike(MgCommentLikeId id, MgComment mgComment, User user, Date cdate) {
       this.id = id;
       this.mgComment = mgComment;
       this.user = user;
       this.cdate = cdate;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="commentId", column=@Column(name="comment_id", nullable=false) ), 
        @AttributeOverride(name="uid", column=@Column(name="uid", nullable=false) ) } )
    public MgCommentLikeId getId() {
        return this.id;
    }
    
    public void setId(MgCommentLikeId id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="comment_id", nullable=false, insertable=false, updatable=false)
    public MgComment getMgComment() {
        return this.mgComment;
    }
    
    public void setMgComment(MgComment mgComment) {
        this.mgComment = mgComment;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="uid", nullable=false, insertable=false, updatable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cdate", nullable=false, length=19)
    public Date getCdate() {
        return this.cdate;
    }
    
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }




}


