package com.allets.backend.data.server.entity.common;// default package
// Generated 2015. 8. 15 오후 5:46:57 by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="USER"
    ,catalog="allets_common"
    , uniqueConstraints = @UniqueConstraint(columnNames="hash") 
)
public class User  implements java.io.Serializable {


     private Long uid;
     private String name;
     private String sex;
     private String birthday;
     private Date cdate;
     private String email;
     private String password;
     private String photo;
     private String hash;
     private String level;
     private String introMessage;
     private String status;
     private Date notiCheckDate;
     private int age15plus;
     private Set<MgCommentLike> mgCommentLikes = new HashSet<MgCommentLike>(0);
     private Set<MgContents> mgContentses = new HashSet<MgContents>(0);

    public User() {
    }

	
    public User(Date cdate, String status) {
        this.cdate = cdate;
        this.status = status;
    }
    public User(String name, String sex, String birthday, Date cdate, String email, String password, String photo, String hash, String level, String introMessage, String status, Date notiCheckDate, int age15plus, Set<MgCommentLike> mgCommentLikes, Set<MgContents> mgContentses) {
       this.name = name;
       this.sex = sex;
       this.birthday = birthday;
       this.cdate = cdate;
       this.email = email;
       this.password = password;
       this.photo = photo;
       this.hash = hash;
       this.level = level;
       this.introMessage = introMessage;
       this.status = status;
       this.notiCheckDate = notiCheckDate;
       this.age15plus = age15plus;
       this.mgCommentLikes = mgCommentLikes;
       this.mgContentses = mgContentses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="uid", unique=true, nullable=false)
    public Long getUid() {
        return this.uid;
    }
    
    public void setUid(Long uid) {
        this.uid = uid;
    }
    
    @Column(name="name", length=256)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    @Column(name="sex", length=1)
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    
    @Column(name="birthday", length=45)
    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cdate", nullable=false, length=19)
    public Date getCdate() {
        return this.cdate;
    }
    
    public void setCdate(Date cdate) {
        this.cdate = cdate;
    }
    
    @Column(name="email", length=60)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="password", length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="photo", length=4000)
    public String getPhoto() {
        return this.photo;
    }
    
    public void setPhoto(String photo) {
        this.photo = photo;
    }
    
    @Column(name="hash", unique=true, length=32)
    public String getHash() {
        return this.hash;
    }
    
    public void setHash(String hash) {
        this.hash = hash;
    }
    
    @Column(name="level", length=10)
    public String getLevel() {
        return this.level;
    }
    
    public void setLevel(String level) {
        this.level = level;
    }
    
    @Column(name="intro_message", length=200)
    public String getIntroMessage() {
        return this.introMessage;
    }
    
    public void setIntroMessage(String introMessage) {
        this.introMessage = introMessage;
    }
    
    @Column(name="status", nullable=false, length=10)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="noti_check_date", length=19)
    public Date getNotiCheckDate() {
        return this.notiCheckDate;
    }
    
    public void setNotiCheckDate(Date notiCheckDate) {
        this.notiCheckDate = notiCheckDate;
    }
    
    @Column(name="age15plus")
    public int getAge15plus() {
        return this.age15plus;
    }
    
    public void setAge15plus(int age15plus) {
        this.age15plus = age15plus;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="user")
    public Set<MgCommentLike> getMgCommentLikes() {
        return this.mgCommentLikes;
    }
    
    public void setMgCommentLikes(Set<MgCommentLike> mgCommentLikes) {
        this.mgCommentLikes = mgCommentLikes;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="user")
    public Set<MgContents> getMgContentses() {
        return this.mgContentses;
    }
    
    public void setMgContentses(Set<MgContents> mgContentses) {
        this.mgContentses = mgContentses;
    }




}


